### ISSUE TITLE
How to require an specific OS

### ISSUE THREAD

**Issue by macintoshplus** [php/pie#106]
The Win32Service PHP extension can be built and used only on the Microsoft Windows operating system.

How to specify this constraint on `composer.json` file?

**Comment by asgrim** [comment]
Not possible at the moment, but something we can look into :+1:

**Comment by alexandre-daubois** [comment]
I'd be interested in having a look at this feature! What about the following syntax?

```json5
{
    "name": "myvendor/myext",
    "php-ext": {
        "extension-name": "myext",
        "configure-options": [
            // ...
        ],
        "os-families": ['Windows', 'Darwin'] // not compatible with Linux here for example
    }
}
```

The values contained in `os-families` would have to match [`PHP_OS_FAMILY`](https://www.php.net/manual/en/reserved.constants.php#constant.php-os-family).

Also, it would be possible to use the wildcard, like `"os-families": ["*"]` (or `"os-families": "*"`?) if one wants to be explicit on supporting all operating systems.

**Comment by Seldaek** [comment]
I think it'd be good to have a way to negate something if you want to closely match PHP_OS_FAMILY, because I suspect most things are gonna be Windows-only, Linux/BSD/Solaris/Darwin-only, or everything. I don't think there are many that support everything except Solaris or everything except BSD.

So it could be nicer with `["!Windows"] or something? I'm just thinking it would suck if people list Linux and forget to include BSD/Solaris/Darwin and then things turn out not installable for no good reason.

**Comment by alexandre-daubois** [comment]
I agree with you, by reading at your comment it feels more natural to me to work with a blacklist instead of a whitelist. Also it saves us from handling the wildcard. I'd rather use `os-families-exclude` instead of the bit-less explicit `!` operator indeed.

**Comment by asgrim** [comment]
Some examples for reference:

only Win:

```
"os-families-exclude": ["BSD", "Darwin", "Solaris", "Linux", "Unknown"]
```

only non-Win:

```
"os-families-exclude": ["Windows"]
```

only OSX:

```
"os-families-exclude": ["Windows", "BSD", "Solaris", "Linux", "Unknown"]
```

**Comment by Seldaek** [comment]
So what I was suggesting is to include BOTH options sorry it was clearly not clear :D

only Win:

```
"os-families": ["Windows"]
```

only non-Win:

```
"os-families-exclude": ["Windows"]
```

only OSX:

```
"os-families-exclude": ["Darwin"]
```

That way you can target whatever you want with the least amount of listing-distros and possibly forgetting things.

Obviuosly the "Unknown" wildcard is a bit problematic here.. But I guess those fall in the category of "rather just allow it and see if it builds 🤷🏻‍♂️ "?

**Comment by macintoshplus** [comment]
I’m okay to use both keys. The wildcard or “Unknown” is not necessary.

If the extension maintainer wants to exclude the unknown OS, it must list all included OS.

If the extension maintainer wants to include “unknown” it uses the exclude key or nothing.

IMO it’s necessary to make an exhaustive list of OS names used in the lists.

**Comment by asgrim** [comment]
> IMO it’s necessary to make an exhaustive list of OS names used in the lists.

This list is already defined: https://www.php.net/manual/en/reserved.constants.php#constant.php-os-family

That list is where `Unknown` comes from.

One thing that should be defined is the behaviour if both keys are used, a few examples:

```json
{
  "php-ext": {
    "os-families": ["Windows"],
    "os-families-exclude": ["Windows"]
  }
}
```

```json
{
  "php-ext": {
    "os-families": ["Windows", "Linux"],
    "os-families-exclude": ["Linux"]
  }
}
```

I would suggest that perhaps the most natural method for processing would be (pseudo-code):

```
allowedPlatforms = Windows BSD Darwin Solaris Linux Unknown

if "os-families" is specified: replace allowedPlatforms with the list

if "os-families-exclude" is specified: subtract from the allowedPlatforms
```

**Comment by Seldaek** [comment]
I think I'd declare it in the json schema as being a oneOf, so that either key should be provided, but not both, and probably need to check in the loader code to throw if both are provided because this is nonsense, even if we can reconcile it per your rules,  it's just clearer to disallow it IMO.

**Comment by asgrim** [comment]
That is probably safer :100: :+1:

**Comment by macintoshplus** [comment]
Both keys are declared nonsense. However, the maintainer must check if the composer.json is valid before tagging the version.

A command `validate`  must be added to help to validate the file.

**Comment by alexandre-daubois** [comment]
I updated https://github.com/ThePHPF/pie-design/pull/29/files to reflect our discussion.

@macintoshplus the `validate` command seems a nice idea to me. This may be worth discuss about it in a new issue 🙂

**Comment by asgrim** [comment]
> A command `validate` must be added to help to validate the file.

`composer validate` already exists

**Comment by macintoshplus** [comment]
Cool, less code to write. But, it's interesting to add this information to the documentation. Right?
