### ISSUE TITLE
Discussion on the x86_64 code usage for Intel 64-bit architecture

### ISSUE THREAD

**Issue by macintoshplus** [php/pie#108]
I am opening this ticket to discuss Intel's 64-bit architecture code. The goal of my remarks is not to break everything but to expose the consequences that can result from changes related to the use of Pie on a PHP extension with Windows.

Even if the `x86_64` code seems more correct to me to designate Intel's 64-bit architecture. The `x64` code is more commonly used and requires less translation.

A lot of extension CI works with the `x64` code, it is also used for the libraries needed for Windows extensions as well as for compiling PHP itself on Windows.

I naively thought that it was only related to the documentation hence my PR #107. However, I realized that it was also in the PIE code.

I think it would be interesting to specify in the required elements of the `composer.json` file the libraries needed for the extension. These dependencies would allow us to check for security vulnerabilities and during compilation, retrieve the source code or binary/SDK automatically.

Is this choice of code for Intel's 64-bit architecture only related to the name of the zip archive and the DLL or will it later be propagated to all library names?

**Comment by asgrim** [comment]
As I mentioned on your PR, this was already discussed in an existing issue #87, you have created a duplicate now. Closing this, please discuss on the existing issue #87.
