### ISSUE TITLE
Question: siloed extensions for shared hosting?

### ISSUE THREAD

**Issue by JensRoland** [php/pie#144]
One of the major benefits of PHP still in 2024 is the fact that it comes preinstalled on basically every cheap shared web host; any hosting service that lets you run WordPress (i.e. all of them) will let you run your own PHP code. This is a superpower.

Now, most hosting providers will have a basic set of common PHP extensions installed, but invariably as a power user you'll run into some extension that is missing, and the hosting provider will be understandably reluctant to install additional software on their servers unless a ton of customers are asking for the same extension.

So as a PHP developer on shared hosting, we are often faced with the situation that anything that comes in a Composer package is fine, but if our code requires a PECL extension, we're limited by the hosting provider.

So the question is: does/will PIE silo extensions in a way that would allow devs on shared hosting to install PIE-compatible extensions in a way that hosting providers could permit (without jeopardizing their business / cross-contaminating other tenants' apps)?

This feature would be another superpower for PHP.

**Comment by asgrim** [comment]
:100: PIE's initial goal/MVP is a 1:1 replacement for PECL; however, this is definitely something we'd like to do "at some point" - see ThePHPF/pie-design#5 . There are challenges within PHP itself and how extensions are loaded though (noted there also).

I'm closing this issue though, as I'd like to keep discussion about that in one place :arrow_right: ThePHPF/pie-design#5 :)

Thank you!
