### ISSUE TITLE
Docker bin image not yet available

### ISSUE THREAD

**Issue by jnoordsij** [php/pie#151]
The current version of usage docs mention the possibility of installation of the binary through Docker. However, since this effort landed after the last release, the image is not available just yet, making the current state of documentation slightly confusing. However, as soon as the next release hits, this issue should be automatically resolved.

Another way to solve this would be to retroactively manually build the Docker image for the 0.2.0 release, although that might be less preferable.

My intention with this issue is mainly to allow for notifying others who might attempt to, just like me, pull the image and run into some minor confusion.

**Comment by jnoordsij** [comment]
@asgrim thanks for the new release! It seems that although the Docker image was built (https://github.com/php/pie/actions/runs/12478762728/job/34826830835), it is not published publically (https://github.com/orgs/php/packages?repo_name=pie):
```
> docker pull ghcr.io/php/pie:0.3.0-bin
Error response from daemon: failed to resolve reference "ghcr.io/php/pie:0.3.0-bin": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aphp%2Fpie%3Apull&service=ghcr.io: 401 Unauthorized
```

Probably this is some GitHub setting that needs to be setup accordingly?

**Comment by asgrim** [comment]
Will check into it, thanks

**Comment by asgrim** [comment]
This has now been fixed, thank you :)

```bash
$ docker logout ghcr.io
Removing login credentials for ghcr.io
$ docker pull ghcr.io/php/pie:0.3.0-bin
0.3.0-bin: Pulling from php/pie
4a612d3ddc7e: Pull complete 
Digest: sha256:1045520f7a798590882e5df7d672fdb287451ff0bf26a2f351ace8f300d937ab
Status: Downloaded newer image for ghcr.io/php/pie:0.3.0-bin
ghcr.io/php/pie:0.3.0-bin
$ gh attestation verify oci://ghcr.io/php/pie:0.3.0-bin --repo php/pie
Loaded digest sha256:1045520f7a798590882e5df7d672fdb287451ff0bf26a2f351ace8f300d937ab for oci://ghcr.io/php/pie:0.3.0-bin
Loaded 1 attestation from GitHub API

The following policy criteria will be enforced:
- OIDC Issuer must match:................... https://token.actions.githubusercontent.com
- Source Repository Owner URI must match:... https://github.com/php
- Source Repository URI must match:......... https://github.com/php/pie
- Predicate type must match:................ https://slsa.dev/provenance/v1
- Subject Alternative Name must match regex: (?i)^https://github.com/php/pie/

✓ Verification succeeded!

sha256:1045520f7a798590882e5df7d672fdb287451ff0bf26a2f351ace8f300d937ab was attested by:
REPO     PREDICATE_TYPE                  WORKFLOW                                     
php/pie  https://slsa.dev/provenance/v1  .github/workflows/release.yml@refs/tags/0.3.0
$
```
