### ISSUE TITLE
Consider using a predictable path for downloads

### ISSUE THREAD

**Issue by asgrim** [php/pie#16]
> It downloads it to `/tmp/pie_downloader_66599d860c5bc9.02217405/xdebug-xdebug-b8a7e3e` — it would be nice that instead of the postfix `b8a7e3e` it used the git tag associated with that commit hash.

This is actually the path inside the zip that GitHub gives from the release, so we don't control that part. That said, we could add additional step to move it. Also, we may want to consider using a predictable path, e.g. `$HOME/.pie/sources/xdebug/xdebug/3.4.0alpha1/` instead of a random path.

**Comment by derickr** [comment]
I think these should be downloaded to `/tmp` and not `$HOME/.pie`, but having a predictable path is very useful.

Especially when debugging crashes, as the path is in the symbol information that gdb outputs.

A random value is probably still worth keeping in a higher level path, to avoid race conditions if PIE gets run twice at the same time.

**Comment by asgrim** [comment]
This is going to be moved as part of #48 anyway, so will close this now.
