### ISSUE TITLE
Add `--force` option

### ISSUE THREAD

**Issue by asgrim** [php/pie#17]
The design doc specifies a `--force` option to install a requested version even if we don't think it is compatible.

See: https://github.com/ThePHPF/pie-design?tab=readme-ov-file#--force

**Comment by asgrim** [comment]
Once #48 is done, in theory I think this is just applying the same as `--ignore-platform-reqs` (or some variation thereof)

**Comment by Bellangelo** [comment]
@asgrim Not sure if the issue is "ready" but I noticed that the #48 is closed so I opened a PR for the `--force` option https://github.com/php/pie/pull/165
