### ISSUE TITLE
Licence is missing

### ISSUE THREAD

**Issue by asgrim** [php/pie#52]
The project currently does not have a licence specified.

Whilst I assume this would be a PHP 3.01, opinions are welcomed if there are compelling arguments to use a different licence.

**Comment by nielsdos** [comment]
See https://wiki.php.net/rfc/php_license_update
The intention seems to be to move away from the PHP specific license on the long term, and for good reasons.

**Comment by asgrim** [comment]
> See https://wiki.php.net/rfc/php_license_update The intention seems to be to move away from the PHP specific license on the long term, and for good reasons.

Thank you - yes I'd forgotten about that proposal :+1:
