### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by thorsten** [php/pie#56]
PIE looks quite promising, thank you very much for starting the project. What about providing a nightly build for a fresh dev release every day?

**Comment by asgrim** [comment]
Hey @thorsten we do have a GitHub Action whose build artefact is the PHAR build, e.g. https://github.com/php/pie/actions/runs/11029347118#artifacts although it's a bit of a faff to get to (i.e. find the latest commit, find the pipeline for it, go to artefacts, download and extract etc) so maybe there could be some improvements to find 👍

**Comment by thorsten** [comment]
Thanks for the fast response @asgrim, I followed the README and I didn't see any releases on https://github.com/php/pie/releases.

**Comment by asgrim** [comment]
Yeah there *will* be 😂 pre-empting the process a little, we're not far off tagging a first alpha type release I think!

**Comment by thorsten** [comment]
Awesome!

**Comment by asgrim** [comment]
Note to self:

 - This API call will get the download URL: `curl -s "$(curl -s "https://api.github.com/repos/php/pie/actions/workflows/continuous-integration.yml/runs?per_page=1&branch=main&event=push&status=success" | jq -r '.workflow_runs[0].artifacts_url')" | jq -r '.artifacts[0].archive_download_url'`
 - However, to download the actual archive you need to be authenticated (you get 403 if you try to curl the URL output from the above command if authenticated)

**Comment by asgrim** [comment]
Nightly PHAR is now linked too :+1:

**Comment by thorsten** [comment]
Thanks, works perfect! Now I have to wait for #32
