### ISSUE TITLE
type in composer.json

### ISSUE THREAD

**Issue by sy-records** [php/pie#64]
When using pie, the type needs to be set to `php-ext` in composer.json, but the default is `library`.

Can I still use `composer require` when the type is set to `php-ext`?

```bash
composer require swow/swow

pie install swow/swow
```

https://github.com/swow/swow/blob/develop/composer.json

**Comment by asgrim** [comment]
At the moment, yes, but I have no idea if that will change. `pie` does a check to ensure the type is `php-ext` or `php-ext-zend`, so you cannot install a type `library` with PIE; but you can currently install a `php-ext` using `composer` (although it won't actually install the extension, it will just place the files in `vendor/` as with any other regular PHP library

**Comment by Seldaek** [comment]
I would not rely on this working in the future though. While there are no concrete plans right now, a long term potential future includes Composer allowing you to require exts and triggering install from `pie` or something.

It sounds to me much cleaner to have an extension specific package, but if you wanna risk it feel free.

**Comment by TimWolla** [comment]
> I would not rely on this working in the future though.

It would probably be useful if composer would remain able to install PIE extensions, because then the stubs would not need to be placed in a separate repository / in a separate package, preventing them from going out of sync.

**Comment by Seldaek** [comment]
This is already gone as composer filters out ext packages. Maybe we will find a solution later for this but right now seems safer to ignore
