### ISSUE TITLE
Which namespace to use for PECL packages in the PHP organization?

### ISSUE THREAD

**Issue by cmb69** [php/pie#65]
This issue came up recently in https://github.com/php/pecl-file_formats-yaml/pull/88#pullrequestreview-2313716331. Since it likely affects a lot of packages, I think it's worthwhile to track it here.

**Comment by asgrim** [comment]
Yeah no decision as such has been made, so maybe `pecl` is the best bet?

**Comment by asgrim** [comment]
Note, affects so far:

 - https://github.com/php/pecl-file_formats-yaml/pull/88
 - https://github.com/php/pecl-datetime-timezonedb/pull/12 (arguably, this one does really belong in `php/` namespace, perhaps?)
 - https://github.com/php/pecl-encryption-mcrypt/pull/20

**Comment by cmb69** [comment]
The timezonedb is already part of php-src; the PECL packages are just so users can update this, if they want to (works as drop-in replacement). So in my opinion, this can use the same namespace as other extensions.

**Comment by asgrim** [comment]
Worth noting that this specifically pertains to the "vendor namespace" part of the ["package name"](https://getcomposer.org/doc/04-schema.md#name) for the purposes of submitting the extension onto the Packagist site, **not** the ["extension name"](https://github.com/php/pie/blob/main/docs/extension-maintainers.md#extension-name) (which will remain the same as when it is/was on pecl.php.net).

So, for discussion sake (I am not saying this is the final decision), lets say we used the **package name** of `pecl/timezonedb` in `composer.json`, the **extension name** is still [`timezonedb`](https://github.com/php/pecl-datetime-timezonedb/blob/0a43c92bbc1ef71d21e8f5f59d71f4e7325f0124/composer.json#L10) as it always has been [historically](https://pecl.php.net/package/timezonedb):

**Comment by asgrim** [comment]
No further comments, so I'll update the three affected repos to use `pecl/` namespace.

**Comment by remicollet** [comment]
Notice: use pecl as vendor name is not easy, see https://github.com/composer/packagist/issues/1496

**Comment by asgrim** [comment]
Just for reference, some PHP Foundation discussion happened, the reference link is [here](https://phpfoundation.slack.com/archives/C06D9CAJYNS/p1726729781201809). Apologies for the private link, but just wanted to "bookmark" it in a place relevant to the conversation.
