### ISSUE TITLE
Expected PDB name is incorrect and disagrees with docs

### ISSUE THREAD

**Issue by asgrim** [php/pie#71]
The [maintainer docs](https://github.com/php/pie/blob/main/docs/extension-maintainers.md#contents-of-the-windows-zip) state:

> * `php_{extension-name}.pdb` - this will be moved alongside
  the `C:\path\to\php\ext\php_{extension-name}.dll`

This implies the PDB name should be something like `php_xdebug.pdb`; however, PIE is incorrectly expecting the PDB name to be aligned with the DLL:

https://github.com/php/pie/blob/eaf77ea181f44c7711887474c4f33501a17cb39f/src/Installing/WindowsInstall.php#L39

( related discussion: https://github.com/mongodb/mongo-php-driver/pull/1732#discussion_r1804706568 )

**Comment by derickr** [comment]
I don't think I make pdbs for Xdebug though? I do need to so that actually... But don't know how.

Does @shivammathur 's new GitHub action support it?

**Comment by shivammathur** [comment]
Yes, php-windows-builder builds the extension with the pdb file, but it follows the naming scheme for both the dll and the pdb file.

**Comment by shivammathur** [comment]
The DLL file and the PDB files for the extension should have the same name for the following reasons.

- As a convention the PDB file with the same name as the DLL is the symbol file for it in the package, as that is how they are generated.
- There might be other DLL and PDB files from the dependencies and cause confusion if the names do not match.

So, I think we should change the docs for this that both files will follow the naming scheme we decided. On installation pie will rename them to `php_<extension>.dll` and `php_<extension>.pdb` and place them in the `ext` directory.

**Comment by asgrim** [comment]
Thanks for clarifying. I will update the docs accordingly

**Comment by cmb69** [comment]
Note that you cannot arbitrarily rename PDB files. The path of the PDB is stored in the executable (DLL or EXE), and looked up automatically when debugging. To my knowledge, there is no problem to put the executable and its PDB in another folder. It is even possible to put the PDBs in a different folder than the executables and tell the debugger in which folder to search for PDBs (inconvenient, though). However, you must not change the basename.

**Comment by asgrim** [comment]
> Note that you cannot arbitrarily rename PDB files. The path of the PDB is stored in the executable (DLL or EXE), and looked up automatically when debugging. ... However, you must not change the basename.

Yep, that is my understanding too; the PDB is placed alongside the DLL, and is named in the same way (e.g. `php_xdebug.dll` and `php_xdebug.pdb` in the same directory).

**Comment by asgrim** [comment]
Hmm; @shivammathur how are these built? :thinking: @cmb69 seems to have a point (although I haven't checked it out myself yet)

**Comment by shivammathur** [comment]
They are built as `php_xdebug.dll` and `php_xdebug.pdb` and then while packaging for pie, they are renamed as per the naming scheme, and thus the need for renaming them back during the install.

I agree with the issue when someone manually downloads the builds and does not use pie.
