### ISSUE TITLE
Optionally output build progress

### ISSUE THREAD

**Issue by asgrim** [php/pie#77]
source; https://github.com/php/pie/pull/76#issuecomment-2435341063

> @asgrim see https://github.com/asgrim/pie/pull/2
> 
> I really think (especially in case of long build) user should be able to follow what happen

Perhaps if the `-v` option is given, to write out phpize/configure/make output, as per Remi's suggestion

**Comment by remicollet** [comment]
To be clear about my initial proposal:

**For now**: the task output is displayed when the task ends

**Proposal**: display the output during the run, especially for long task (configure in ~1', make in minutes), as without output, user may think the process is stalled.

Verbosity is another choice/discussion

For now: only displayed when using very verbose mode (-vvv)

IMHO: always (not in quiet mode, `-q`), but I'm probably not a standard user.

**Comment by asgrim** [comment]
This will be done as part of #48 

I think the current "simple" output is fine for most users, but we would display the streamed output of phpize/configure/make with a single `-v`. We can always revisit it if that's not the case! :+1:
