### ISSUE TITLE
brew package for pie

### ISSUE THREAD

**Issue by oleg-andreyev** [php/pie#98]
I think it would be great to create brew package for pie.

**Comment by asgrim** [comment]
That may be a long way off in the future I think, if at all. A phar is the intended distribution method at the moment, no current plans for other methods of distribution.

**Comment by TimWolla** [comment]
> no current plans for other methods of distribution.

Publishing it as a composer package to packagist would be convenient, as it would just be a `composer install` away when the CI already has composer installed. No need to fumble around with signing keys and similar.

**Comment by SRWieZ** [comment]
Installing with either `composer global require php/pie` or `brew install pie` would, I believe, facilitate adoption.

**Comment by asgrim** [comment]
I have created a separate issue #136 for the question of Composer support. Thank you folks

**Comment by welcoMattic** [comment]
The `brew` formula is available [here](https://github.com/Homebrew/homebrew-core/blob/2311fe0d7f057806114f8b0c59d128b44bf7691f/Formula/p/pie.rb)

**Comment by asgrim** [comment]
Sounds like this is done already then :heavy_check_mark:  thanks.

**Comment by methbkts** [comment]
Maybe we can add it to the docs ?

**Comment by remicollet** [comment]
Notice: RPM users can also use their package manager (dnf) to install/update pie

See https://src.fedoraproject.org/rpms/pie

**Comment by asgrim** [comment]
> Maybe we can add it to the docs ?

I don't think we need to add it to the docs; that would imply we officially support it, but that is not something we currently maintain, nor do I know anything about `brew` I'm afraid.

**Comment by tillkruss** [comment]
@asgrim Maybe we could mention it exists but is not officially supported? Happy to open a PR.

**Comment by asgrim** [comment]
I really don't think it is necessary. People who use brew know where to look anyway, so it doesn't add any value.

**Comment by asgrim** [comment]
In fact thinking more, I'd prefer not to recommend brew at all; we have verification for `self-update` that ties into GH's build provenance and attestation system to allow downstream users of PIE to verify the authenticity of the PHAR, which we cannot guarantee with third party package managers (unless they build that mechanism in).
